### ISSUE TITLE
Delphinus install itself as the second last item in the tools menu

### ISSUE THREAD

**Issue by NickRing** [Memnarch/Delphinus#10]
Delphinus install itself as the second last item in the tools menu, which means if you have tools installed, it messes the order up. See attached image.

![image](https://cloud.githubusercontent.com/assets/8101671/9564867/2d9f5690-4ef8-11e5-9102-6509a3f179f8.png)

**Comment by Memnarch** [comment]
it currently adds itself when it's loaded. So the loading order specifies it. But maybe i can put it after configure tools. have to look for it.

**Comment by Memnarch** [comment]
From now on, it installs itself before the ConfigureTools MenuItem.
