### ISSUE TITLE
Cannot compile in Delphi 10 Seattle

### ISSUE THREAD

**Issue by PeterPanino** [Memnarch/Delphinus#15]
[dcc32 Error] DN.HttpClient.WinHttp.pas(171): E2033 Types of actual and formal var parameters must be identical

Solution:
LRead, LWritten: UInt64;

**Comment by PeterPanino** [comment]
Other bug:

[dcc32 Error] E1026 File not found: 'DelphinusImages.res'

**Comment by Memnarch** [comment]
please only one bug at a time/ticket ;)
Ok for this time.

**Comment by Memnarch** [comment]
About the missing .res file:
Is there a dres file? Cause other people reported seattle to work correctly (before i changed to WInHttp) but i din't change the way resources are added to the project iirc. It is expected that the resourcecompiler is triggered.

**Comment by PeterPanino** [comment]
No, there is no dres file in the downloaded zip file.

**Comment by Memnarch** [comment]
ofcourse there is not, the question is, does the IDE generate one when opening compiling?
The Project includes the RC files and generates the res. As i said, it worked for other Seattle user

**Comment by PeterPanino** [comment]
OK, it didn't work for me.

**Comment by Memnarch** [comment]
Okay this resourcestuff was totally my bad. Sorry!
It seems i accidentally removed the rc-file from the XE6 project at some point. Please close if everything works
