### ISSUE TITLE
Package output path Win32 subfolder

### ISSUE THREAD

**Issue by jairgza** [Memnarch/Delphinus#17]
Trying to install VirtualTreeView but i get the error:

Error: Can't load package C:\Users\Public\Documents\Embarcadero\Studio\15.0\Bpl\Win32\VirtualTreesD21.bpl.

The "standar" path for win32 bpl files is  **C:\Users\Public\Documents\Embarcadero\Studio\15.0\Bpl**  ,why delphinus (or virtualtreeview ?) is creatin a Win32 subfolder ?  Its a bug or feature ?

I guess this is because the designtime package when installing is not finding the runtime package, but I'm not sure

**Comment by Memnarch** [comment]
Okay the Win32-Subfolder is not supposed to be there for Win32-packages.
15.0 is XE8 right?

Is the BPL really stored at this path or is it stored at the expected path but it tries to load the package from the subfolder?

Can you dump this registryKey for me:
HKEY_CURRENT_USER\Software\Embarcadero\BDS\15.0\Library\Win32

**Comment by jairgza** [comment]
15.0 is XE7

The bpl is stored in the Win32 subfolder

Here is the dump for registryKey:
HKEY_CURRENT_USER\Software\Embarcadero\BDS\15.0\Library\Win32

[Reg_LibraryWin32.txt](https://github.com/Memnarch/Delphinus/files/195904/Reg_LibraryWin32.txt)

**Comment by Memnarch** [comment]
Hi,
Okay that's strange. 
Currently no access to XE7 so i modified the delphinus files to use the XE7 projects for XE6 and it worked (WIndows 10 aswell). SO it does not seem to be project related(as you have guessed, it might be your environment)

What is displayed for the WIn32 Target as BPLOutput in:
IDE->Tools->Options->Library

What happens when you compile the project manually from IDE?

**Comment by jairgza** [comment]
>>What is displayed for the Win32 Target as BPLOutput in:
>>IDE->Tools->Options->Library

Package output directory:
**$(BDSCOMMONDIR)\Bpl**

DCP output directory:
**$(BDSCOMMONDIR)\Dcp**


>>What happens when you compile the project manually from IDE?

It compiles fine and the bpl,dcp files are in the correct paths


>>Have you specified eny EnviromentVariables of Delphi for your Windows?

No, not by me, only the Paths added automatically when installs the IDE


This is the dump from the registry:
[Win10_x64_LibraryReg.txt](https://github.com/Memnarch/Delphinus/files/198886/Win10_x64_LibraryReg.txt)



Diging in the delphinus code, I add to the log the obtained paths
In DN.Installer.pas - function TDNInstaller.ProcessProject, just before FCompiler.Compile(AProject.FileName); added

DoMessage(mtNotification, FCompiler.BPLOutput);
DoMessage(mtNotification, FCompiler.DCPOutput);

The log shows the paths appending the **"$(Platform)"** variable
$(BDSCOMMONDIR)\Bpl\$(Platform)
$(BDSCOMMONDIR)\Dcp\$(Platform)

This is the log file:
[log.txt](https://github.com/Memnarch/Delphinus/files/198887/log.txt)

**Comment by jairgza** [comment]
I think I found the problem

In source DN.ToolsApi.Extension.pas
procedure TDNEnvironmentOptionsService.LoadPlatforms;

	LReg.RootKey := HKEY_CURRENT_USER;
    LLibraryKey := TPath.Combine(LBase ,CLibraryKey);
    if LReg.OpenKey(LLibraryKey, False) then
    begin
      LReg.GetValueNames(LNames);
      //we are on a Win32-Only Delphi
      if LNames.Count > 0 then
      begin
        ...
		...
      end
      else
      begin
        //we are on a multiplatform Delphi
		...
		...
	  end;
	  
You are trying to detect if the IDE is MultiPlatform or Win32-Only
by checking if the registry key "Library" has no elements, but I realized that
one component I have, write into that key (may be is a useless value, i dont know, but its there) so Delphinus think it's a Win32-Only IDE
![sin titulo](https://cloud.githubusercontent.com/assets/14021653/14197411/4a67802c-f78b-11e5-9109-11f5e993448e.jpg)

I removed the subkey and all works fine.  But I would prefer not to have to edit the registry

Do you think there is better way to know what kind of IDE is running ?  

regards

**Comment by Memnarch** [comment]
Ahh thanks!
Yes this information there is useless. On Multiplatform IDEs the Library content is ignored and values are read only from their platform keys. Which component is this that writes there o.O

**Comment by jairgza** [comment]
ZipForge component
many thanks

**Comment by Memnarch** [comment]
BTW at this point, i am really(!) curious why i didn't check for CompilerVersion > 22 (Since XE is the only SInglePlatform IDE with the old ToolsAPi i support) XD

**Comment by Memnarch** [comment]
Hope this fix works for you. Can you verify?

**Comment by jairgza** [comment]
Ok It is working now, thanks for your time
Best regards
