### ISSUE TITLE
Publishing from a repo marked as "fork"

### ISSUE THREAD

**Issue by micha137** [Memnarch/Delphinus#19]
Publishing-your-Project-for-Delphinus sensibly mentions the condition:

> it must be the "original" Repository, Repositories marked as fork are not listed to avoid flooding

I now have a forked project and want to publish it for Delphinus.  I suggest an override in the Delphinus.Info.json that allows to override this logic for example by stating the URL of the canonical repository.

**Comment by Memnarch** [comment]
this is more of a search problem. I request the list by executing a serach on the github api which (by default) excludes forks. If i enable forks, i get hundrets of results. I'll have to inspect all of them just to find those 12 we currently have. I know this is a bit frustrating and i am open for ideas. But unlocking the search will degrade performance quite heavy!

A workaround you could use is creating a mirror repository. You work on the fork and mirror finished results to the other repo. (by just pushing from fork to mirror it is still quite simpel)

**Comment by micha137** [comment]
You are right, I will try the mirroring.
