### ISSUE TITLE
Installation fail

### ISSUE THREAD

**Issue by kazalex** [Memnarch/Delphinus#2]
Delphi XE/6, Windows XP SP3. Error when trying Install of Delphinus package:
---------------------------
Error
---------------------------
Unable to create directory.
---------------------------
OK   
---------------------------

**Comment by Memnarch** [comment]
Delphinus uses the Environmentvariable %LocalAppdata%, which does not exist prior to Vista. Try to create this one and point to a directory(and empty one to be sure) where Delphinus can create files/folders for temporary work/caching.

**Comment by kazalex** [comment]
Problem with installing of Delphinus package, not other packages via Delphinus.

**Comment by Memnarch** [comment]
So you compile thze package(which works), click install, and it throws this message?(As a messagebox or in the messagewindow?). Really confused right know, as there is no directory created until someone presses refresh.

**Comment by kazalex** [comment]
Problem really in environment variable, but arise she at moment of installation of Delphinus package (even if to try installing compiled package Dephinus.bpl). ForceDirectories raise exception:

:7c812fd3 kernel32.RaiseException + 0x52
rtl.System.SysUtils.ForceDirectories('')
rtl.System.SysUtils.ForceDirectories('Delphinus')
rtl.System.SysUtils.ForceDirectories('Delphinus\Github')
Delphinus.DN.PackageProvider.GitHub.TDNGitHubPackageProvider.Create('')
Delphinus.Delphinus.Dialog.TDelphinusDialog.RecreatePackageProvider
Delphinus.Delphinus.Dialog.TDelphinusDialog.Create(nil)
Delphinus.Delphinus.Controller.TDelphinusController.Create
Delphinus.Delphinus.Main.Delphinus.Main
rtl.System.InitUnits
rtl.System._PackageLoad(???,???)
:09251442 Sysinit::__linkproc__ PackageLoad(Table=????)

**Comment by Memnarch** [comment]
oh!
Thanks. I'll put the information of the non existing environmentvariable to the wiki for XP. (As the user should select where to store the data since there is no LocalAppData).

Is this solved if you set the enviromentvariable?
('Ill then close the issue)

**Comment by kazalex** [comment]
>I'll put the information of the non existing environmentvariable to the wiki for XP

Maybe will better to use other variable when LocalAppData was not found? AppData, for example?

**Comment by Memnarch** [comment]
that's an option, too. I'll implement this.

**Comment by kazalex** [comment]
Thanks ;)

**Comment by Memnarch** [comment]
i implemented a change, which will use a proper API function that works on XP and later. Please remove the LocalAppData environmentvariable and retry, and tell me if this works.

**Comment by kazalex** [comment]
Now works. I tested it on clean XP SP3 VM with XE6.
