### ISSUE TITLE
publish package

### ISSUE THREAD

**Issue by landrix** [Memnarch/Delphinus#20]
https://github.com/Memnarch/Delphinus/wiki/Publishing-your-Project-for-Delphinus

Which readme do you mean? ReadMe.md ?

**Comment by Memnarch** [comment]
In short: Yes.

Longstory:
The readme which is displayed by github(when you visit the projectpage). Github has some rules on how you can add a readme to your project. It doesn't matter which one, the Github API will provide me the active one.

**Comment by Memnarch** [comment]
if it is about The-Drag-and-Drop-Component-Suite-for-Delphi
 not being listed:

There is something very strange going on. The most recent changes to your Delphinus files are here:
https://github.com/DelphiPraxis/The-Drag-and-Drop-Component-Suite-for-Delphi/commit/4ab308fbc44433ecee6ca717b9ec5039816ab3fb
https://github.com/DelphiPraxis/The-Drag-and-Drop-Component-Suite-for-Delphi/commit/4b2a2d2f26e9d48dce4bd9edc52f5c7b8be3dc90

In these commits the files are deleted(!?) but Github still shows them when browsing the source online. I haven't checked what the api returns but that history looks wrong o.O (or am i missing something?)

**Comment by landrix** [comment]
yes, there were duplicates, i don't know whats wrong

**Comment by Memnarch** [comment]
https://api.github.com/repos/DelphiPraxis/The-Drag-and-Drop-Component-Suite-for-Delphi/contents/Delphinus.Info.json

Will not give any result. (iirc i use raw.github.com instead of this but this is just strange).

Something must be broken here. Can you reset the repo and reapply the commit you did after deletion?
And by duplicates do you mean you had the same files twice in your repo?

**Comment by Memnarch** [comment]
URGH!
Okay we go casesensitive here. Seems you committed on a casesensitive filesystem. Github provides files Casesensitive(as it seems). But your files have Delphinus.info, Delphinus.install. But Install and Info need capital letters. 

I'll note that in the wiki!

**Comment by landrix** [comment]
i've changed the case

**Comment by landrix** [comment]
and deleted ReadMe.txt

**Comment by Memnarch** [comment]
It's visible again.
