### ISSUE TITLE
Delphinus packager has found packages but not showing them in list

### ISSUE THREAD

**Issue by dimsa** [Memnarch/Delphinus#21]
May be it's only my trouble, but I've got the following:
1) I installed delphinus XE6 in Seatle Upd 1
2) Open it in tools(I was in the Delphinus.bpl project), tried to install something(aggpas or something another that I knew)
3) I've got some error (didn't remember it, I thought that it was because of BPL project). 
4) I pressed Create new cross-platform application
5) Opened Delphinus from tools.
6) Tried to install some packages. Got error on each package "Can not download package"
7) Closed Delphi. 
8) Opened Delphi. Pressed Create New cross-platform application.
9) Opened Delphinus from tools and pressed refresh button
10) I've got progress bar that has enumerated packages.
11) But nothing appeared in list with packages

Then I tried to uninistall and install Delphinus, but nothing had changed.

That's all.

**Comment by Memnarch** [comment]
Mh strange. Without the errors in question it's a bit hard to guess. Can you reproduce them?

Which packages did you try? Some have errors(which is a mistake made by the package-author). Can you try VirtualTreeView?

**Comment by dimsa** [comment]
Yes, I can reproduce it on another computer.

Seatle Upd 1.
1) Installed XE6 Delphinus package
2) Created new multi-device application
3) Opened Delphinus. 
4) Tried to download VirtualTreeView. Got Error:
Downloading Virtual Treeview
Version 6.3.0
Error: failed to download
deleting tempfiles
Error: Installation failed
5) Closed Delphi.
6) Opened Delphi. Opened Delphinus in tools. Pressed refresh button. Got Progress bar with list of packages, but no one is appeared in list.

**Comment by Memnarch** [comment]
Can you attach the Debugger to the Ide and check what happens?

DN.PackageProvider.GitHub.pas
TDNGitHubPackageProvider.Download

You might have to step into the HTTPClient which internally uses WinHTTP and check the errorcode if the Download fails. (Yes, i am sorry that i am not logging it. I'll work on that!)

But maybe it fails when extracting or something else in the Download-Method.

**Comment by ms301** [comment]
Токен от гитхаба писал в настройках Делфинуса?

**Comment by Memnarch** [comment]
Sorry i understand only German and English :(

**Comment by HwapX** [comment]
Same here

**Comment by Memnarch** [comment]
@ms301 Yes, the OAuthToken is written to the Settings(Which is in the registry). The token is used across all Delphinus instances (i.e. When using multiple IDEs in paralell) for the current windows user.

I am currently a bit confused as on where this fails. Is there a difference if you use/not use the OAuthToken?

**Comment by Memnarch** [comment]
@ms301  I tested it on the current Starter (Berlin) and everything works fine. Can you dig into it using the Debugger?

**Comment by ms301** [comment]
@Memnarch, now Delphinus working. All good!

**Comment by dimsa** [comment]
Hello! I've tried it again. Same problem. 
I Installed Delphinus, then Installed VirtualTreeView and all was fine, but after reboot of Delphi Seattle Update 1, I've got clean list. Sorry, I didn't try to debug Delphinus.
![delphinusscreen](https://cloud.githubusercontent.com/assets/6938205/17929327/ec8c60b4-6a29-11e6-92a0-5c1292c71523.png)

**Comment by Memnarch** [comment]
Does this occur with the latest master? Please debug a bit into the PackageProvider.Github unit.

**Comment by sglienke** [comment]
HTTP Result checking FTW. ;)

TDNGitHubPackageProvider.GetReleaseText returns false because the client gets a 403. If you fire the request in the browser you get something like this:

`{
  "message": "API rate limit exceeded for 194.25.32.254. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}`

And then it just exits with False and does not add anything to the overview.

**Comment by bdwilton** [comment]
I think setting the OAuth-Token has worked for me so far

**Comment by rubemrocha** [comment]
how to set oauth token?

**Comment by Memnarch** [comment]
Once Delphinus is installed, when you open the dialog, there is an options button at the top. Follow the link on this wiki page to create your own OAuth token and paste it there :)
https://github.com/Memnarch/Delphinus/wiki/Installing-Delphinus
