### ISSUE TITLE
"ratelimit exceeded" error

### ISSUE THREAD

**Issue by edwinyzh** [Memnarch/Delphinus#26]
Checked out repository, installed on xe4, clicked the Refresh button, and got this error, see the screenshot below:

![2016-10-13_11h14_24](https://cloud.githubusercontent.com/assets/541197/19335528/8e6c83cc-9136-11e6-8fb5-f9fb7379a3c0.png)

**Comment by Memnarch** [comment]
This is explained on my Wiki, see: [Common Errors](https://github.com/Memnarch/Delphinus/wiki/Common-Errors). There is not much i can do about it right now. I am sorry :(. (But i'll still look into it at a later time if there is anything i can do)

**Comment by Memnarch** [comment]
Talked to the Github support. I have to stick to the API and can't workaround it :(
