### ISSUE TITLE
Ratelimit exceeded. Wait for reset.

### ISSUE THREAD

**Issue by turric4n** [Memnarch/Delphinus#29]
Hi, 

When compiled and installed delphinus in RAD Studio Berlin 10.1 and refresh packages. Warning/Error is showed on packagemanager. 
![captura](https://cloud.githubusercontent.com/assets/7852968/19804719/5db80266-9d10-11e6-9262-2bb38994213a.JPG)

**Comment by Memnarch** [comment]
https://github.com/Memnarch/Delphinus/wiki/Common-Errors
