### ISSUE TITLE
DX10.1 upd 1 - Error: Failed to load group / Could not load project

### ISSUE THREAD

**Issue by dslutej** [Memnarch/Delphinus#33]
graphics32 as an example, but tested with several packages.

**Log message:**

Downloading graphics32
Version: HEAD
Copying sourcefolders:
.
Error: Failed to load group C:\Users\Public\Documents\Embarcadero\Studio\18.0\Comps\graphics32\source\Source\Packages\RX1\GR32.groupproj
Error: Could not load Project C:\Users\Public\Documents\Embarcadero\Studio\18.0\Comps\graphics32\source\Source\Packages\RX1\GR32_R.dproj Reason: File not found
Adding Libpathes:
deleting tempfiles
Error: Installation failed

**However, the files are clearly present:**

 Directory of C:\Users\Public\Documents\Embarcadero\Studio\18.0\Comps\graphics32\source\Source\Packages\RX1

2017-01-18  11:38    <DIR>          .
2017-01-18  11:38    <DIR>          ..
2016-12-01  08:02             1 471 GR32.groupproj
2016-12-01  08:02               894 GR32_D.dpk
2016-12-01  08:02             2 175 GR32_R.dpk
               3 File(s)          4 540 bytes
               2 Dir(s)  39 508 004 864 bytes free

Finally, even after failure, the Delphinus will tag packages as installed.

**Comment by Memnarch** [comment]
No, they are not there. only DPK files but no .dproj! It seems some people still don't get how projects work in Delphi :|

Please report this issue to Graphics32.
For the future: Before reporting a problem with a specific package to me, report it to the PackageAuthors. Most of the time(in the past) it was a faulty package.

Packages are currently tagged as installed as i do not do an automatic rollback right now. This option allows you to clean it up manually. But i agree, it should to that by itself.

**Comment by Memnarch** [comment]
Ofcourse if those other packages clearly do have all the files, please append those here.

**Comment by dslutej** [comment]
You are quite correct (and a bit **rude** imho). 

.groupproj is there so I jumped to a conclusion too fast. 

However, Delphinus should not report the package as installed. 

Same with AggPasMod FYI. 

With DWScript:

Downloading DWScript
Version: HEAD
deleting tempfiles
Error: The server returned an invalid or unrecognized response

... and I am out.

**Comment by Memnarch** [comment]
I am sorry! I didn't want to sound rude :(
I wrote that between two tasks at work and just kept it short. 
You are right with the other packages and those are maintained by the same author. He didn't react to my request to fix it in the past. Maybe if someone else adds an issue.

**Comment by micha137** [comment]
Hi,

I'm from Graphics32.

> Error: Could not load Project C:\Users\Public\Documents\Embarcadero\Studio\18.0\Comps\graphics32\source\Source\Packages\RX1\GR32_R.dproj Reason: File not found

I didn't know Delphinus also needs .dproj files.  For my Jenkins installation I also miss .dproj files under version control.  I also know they are generated, of you open a .dpr file with the IDE.  Probably that is why G32 decided to not keep them under version control.

I will ask my fellow developers, whether we can add them.

**Comment by Memnarch** [comment]
Thanks for the Answer.
the dproj are required for a working MSBuild chain and some settings are only stored from within a dproj.

**Comment by Memnarch** [comment]
Hi,
@micha137 any news on the topic?

**Comment by micha137** [comment]
We agreed to add them.  I didn't get to actually do it... the main problem is that I only have Delphi 2010 and XE3 to generate them.  So I want to try https://github.com/errorcalc/PackagesGenerator/ ...

When I add them, I will add all supported platforms, OK.

**Comment by Memnarch** [comment]
No problem :).
BTW you could generate your projectfiles with 2010 or XE3 and reuse them for all versions. Only thing in mind is, if it is the same projectfiles, LibSuffix are not yet autogenerated. You might want to copy them with a proper LibSuffix.

**Comment by micha137** [comment]
OK, I just added all .dproj for Delphi 2010 till RX2, autogenerated by PackageGenerator, which takes care of replacing LibSuffix.  Win64 is a supported platform in the runtime package.  OSX is not supported, because all our packages require the VCL... have to remove OSX from the Delphinus config.
