### ISSUE TITLE
 WebInstaller could show version info of Delphinus

### ISSUE THREAD

**Issue by mWaltari** [Memnarch/Delphinus#36]
Which version installed, and which version it was replaced with.

Now I do not know was there an update or just reinstall of the same version.

**Comment by Memnarch** [comment]
That is, because right now, Delphinus has no version. The installer itself allows to select a version IF one is available. I admit it is a bit confusing right now. I'll think about adding Beta-Releases

**Comment by mWaltari** [comment]
OK
