### ISSUE TITLE
Some properties for Write

### ISSUE THREAD

**Issue by ms301** [Memnarch/Delphinus#46]
Hello! I'm develop UI tools for add Delphinus support in delphi library([Delphinus-its-easy](https://github.com/ms301/Delphinus-its-easy/tree/develop)). 
I'm using _DN.JSonFile.Info_ and _DN.JSonFile.Installation_ for load and save json model. but when i want write data from ui in model - some property disabled for writing. You can change property for write? 
thanks.

**Comment by Memnarch** [comment]
I can look into it, sure :)
