### ISSUE TITLE
Possible access violation when installing.

### ISSUE THREAD

**Issue by NickRing** [Memnarch/Delphinus#5]
In `TDNRegistryEnvironmentOptions.Create` there are two external calls:

````
FRegistryOptions := GetRegistryOptionsObject(GetEnvironmentOptionObject(), ARegistryKey);
FRegistry := GetRegistryOptionsMemIni(FRegistryOptions);
````

If `GetRegistryOptionsObject` returns `nil`, it is passed in to `GetRegistryOptionsMemIni`. However there is no check within the method to see if the object passed in is nil, so it will access violate when the following line is executed:

````
begin
  Result := nil;

  LType := LContext.GetType(ARegOption.ClassType);
````
Where `ARegOption` is the passed in object. The following line should be added after `Result := nil;`

````
if not assigned(ARegOption) then
  Exit;
````

Using XE7.1

**Comment by Memnarch** [comment]
Definetly something to improve. I'll do that. Did it throw an AV? (if it does we've got a problem)

**Comment by NickRing** [comment]
It did throw an AV while trying to install :-(

I finally got around to test Delphinus around midnight (just the best time to, right?) and it wasn't installing because of the AV and by commenting out code, it lead me to the above situation. I haven't had time to read and understand what it was trying to do, sorry :(

**Comment by Memnarch** [comment]
well, that code is quite critical. It gives me access to the seperated environment*options(library-path) for each platform (win32;win64;OSX32) seperately. If this code completely fails, i cant configure the environment when you install a package.

**Comment by NickRing** [comment]
Give me a couple of days and I will try to debug it (full-on weekend :( )

**Comment by Memnarch** [comment]
thank you, that's great :)

**Comment by NickRing** [comment]
Found the issue...

Delphinus assumes that is the registry key exists (in `TDNEnvironmentOptionsService.LoadPlatforms`), that the platform is available. This is not the case for me, as I didn't install the OSX32 platform, as I don't have any OSX32 devices. Because I haven't installed the OSX32 platform, Delphinus is unable to retrieve the OSX32 library path (in `GetRegistryOptionsObject`).

So there is two problems I see:
1. The install process for XE7 is broken, in that it add keys for non-existent platforms. Possibility of getting fix, none.
2. Delphinus doesn't handle missing platforms. Possibility of getting fixed, fairly high.

**Comment by NickRing** [comment]
Created a pull request to overcome this issue.

**Comment by Memnarch** [comment]
merged it. Thanks for providing the fix :)
