### ISSUE TITLE
How to correct or update the existing packages available on Delphinus??

### ISSUE THREAD

**Issue by amjadtbssm** [Memnarch/Delphinus#57]
I was wondering is there a way to update the packages already available on Delphinus?? I was installing SynEdit but it failed a numerous times, upon inspection I found out that the SynEdit folder in comps folder is C:\Users\Public\Documents\Embarcadero\Studio\17.0\Comps\SynEdit\Source\Source instead of C:\Users\Public\Documents\Embarcadero\Studio\17.0\Comps\SynEdit\Source any ideas please??

**Comment by Pawe1** [comment]
**1. What do You mean by "update"?**
You mean to clone repository / make changes or fixex / sideload it?

_:warning: Watch out for issue https://github.com/Memnarch/Delphinus/issues/43 - make sure source folder has same as package before sideloading._

**2. Do You mean that there is a bug in latest SynEdit release?**
Have You reported it to its author?
Maybe make a fork / clone / fix / commit / push / make a pull request with fix? :grin:

**Comment by Memnarch** [comment]
The double SOurce/Source folder is ugly but not an issue. If installation fails for you there seems to be a problem with Synedit(did you install the version of HEAD of it?) or its packagedefinition. As mentioned by Pawe1, best option might be to forward it to the SynEdit-Project.

**Comment by Memnarch** [comment]
The issue already exists. maybe bump it by commenting:
https://github.com/SynEdit/SynEdit/issues/70

**Comment by amjadtbssm** [comment]
Installing both HEAD or release version gives the same error here is a log file. Install from folder didn't work either. I'm updating an old project to Seattle plz help out.

Downloading SynEdit
Version: SynEdit-2.0.9-beta
Copying sourcefolders:
Error: base must be exactly overlapping with folder string to remove it
Source
Error: Failed to load group C:\Users\Public\Documents\Embarcadero\Studio\17.0\Comps\SynEdit\source\Packages\RX\SynEdit.groupproj
Error: File does not exist
Adding Libpathes:
Adding Searchpathes:
Source
Adding Browsingpathes:
Source
deleting tempfiles
Error: Installation failed

**Comment by Memnarch** [comment]
As said above, that is an issue with synedit. They need to fix it on their side atm.

**Comment by Pawe1** [comment]
Try uninstall package / clone / delete `"base": ".",` from `Delphinus.Info.json` and sideload package considering what I said before.
But this is just a temporary workaround.

**BTW this is strange that only available release in SynEdit reposiroty is not a stable one...** :roll_eyes:

**Comment by amjadtbssm** [comment]
Well folks, I found the **Core of the Problem**, its Delphinus.
SynEdit Packages looks for **Source** folder as **"..\..\Source\FileName.pas"**
Whereas Delphinus puts every folder in the source folder.
![synedit](https://user-images.githubusercontent.com/16371511/31385690-90b8c9e6-addd-11e7-8d90-268746087ef8.png)

Is there a way to copy a folder with **Delphinus.Install.json** up one folder of **Source** folder, I mean the install directory.

**Comment by Pawe1** [comment]
@amjadtbssm I wrote correct answer for Your problem:
https://github.com/Memnarch/Delphinus/issues/57#issuecomment-335438608

**Having valid config files shall be the responsibility of repository maintainers.**

**Comment by amjadtbssm** [comment]
@Pawe1 Thanks for the assist, the problem have been solved on *SynEdit* so i'm closing this issue.
Thanks everyone for your help
