### ISSUE TITLE
Linux64 Platform compile without permission

### ISSUE THREAD

**Issue by BakasuraRCE** [Memnarch/Delphinus#62]
Hi,

i just start to install the component "LT Water Effect" in a fresh RAD Studio 10.2.2 and the installation return one error, when i see the log i notice that Delphinus try to compile on Linux64 but the component only have support for windows.

**Windows:** 10 Build 1709

### Log

Downloading LT Water Effect
Version: 1.1.1
Copying sourcefolders:

Compiling LTEffects.dproj
Win32
installed
Warning: Platform IOSDevice64 not supported, skipping
Linux64
Microsoft (R) Build Engine Version 3.5.30729.8833
[Microsoft .NET Framework, Version 2.0.50727.8825]
Copyright (C) Microsoft Corporation 2007. All rights reserved.

Build started 28/12/2017 23:23:59.
Project "C:\Users\Public\Documents\Embarcadero\Studio\19.0\Comps\LT Water Effect\source\Packages\LTEffects.dproj" on node 0 (Build target(s)).
  Creating directory "C:\Users\Public\Documents\Embarcadero\Studio\19.0\Comps\LT Water Effect\lib\Linux64\Release".
BuildVersionResource:
  CodeGear Resource Compiler/Binder
  Version 1.2.2 Copyright (c) 2008-2012 Embarcadero Technologies Inc.
  
  Microsoft (R) Windows (R) Resource Compiler Version 6.0.5724.0
  
  Copyright (C) Microsoft Corporation.  All rights reserved.
  
  
  Deleting file "LTEffects.vrc".
_PasCoreCompile:
  Embarcadero Delphi for Linux 64 bit compiler version 32.0
  Copyright (c) 1983,2017 Embarcadero Technologies, Inc.
LTEffects.dpk(25): warning W1002: Symbol 'IMAGEBASE' is specific to a platform
LTEffects.dpk(30): error E2202: Required package 'vcl' not found
Done Building Project "C:\Users\Public\Documents\Embarcadero\Studio\19.0\Comps\LT Water Effect\source\Packages\LTEffects.dproj" (Build target(s)) -- FAILED.

Build FAILED.

"C:\Users\Public\Documents\Embarcadero\Studio\19.0\Comps\LT Water Effect\source\Packages\LTEffects.dproj" (Build target) (1) ->
(_PasCoreCompile target) -> 
  LTEffects.dpk(25): warning W1002: Symbol 'IMAGEBASE' is specific to a platform

"C:\Users\Public\Documents\Embarcadero\Studio\19.0\Comps\LT Water Effect\source\Packages\LTEffects.dproj" (Build target) (1) ->
(_PasCoreCompile target) -> 
  LTEffects.dpk(30): error E2202: Required package 'vcl' not found

    1 Warning(s)
    1 Error(s)

Time Elapsed 00:00:02.00

Error: Failed
Adding Libpathes:
C:\Users\Public\Documents\Embarcadero\Studio\19.0\Comps\LT Water Effect\lib\Win32\Release
Adding Searchpathes:
Source
deleting tempfiles
Error: Installation failed

**Comment by Pawe1** [comment]
So... Looks like a bug in **LTWaterEffect**

This is a line from package source:
`<Platform value="Linux64">True</Platform>`
Check here: https://github.com/BakasuraRCE/LTWaterEffect/blob/master/Packages/LTEffects.dproj

**Comment by Memnarch** [comment]
Yup, that is a bug in the package. The project says it supports Linux, while it does not.

**Comment by BakasuraRCE** [comment]
I had the idea that the platforms specified in the delphinus files also gave compilation rules.

Thanks for the clarification.
