### ISSUE TITLE
Error trying to install packages from command line

### ISSUE THREAD

**Issue by rrezino** [Memnarch/Delphinus#63]
I'm getting an AV while trying to install packages from command line. 

![error delphinus](https://user-images.githubusercontent.com/19705449/36268437-c042f6ca-1276-11e8-8cec-1728fe8622e1.png)

I'm using Delphi Seattle.

**Comment by Memnarch** [comment]
fixed, should work now :)

**Comment by rrezino** [comment]
it's working now! thanks!
