### ISSUE TITLE
Can't find System.ImageList when installing to XE5

### ISSUE THREAD

**Issue by TCardinal** [Memnarch/Delphinus#74]
When trying to install on XE5 I get the System.ImageList not found. I think that this was introduced in XE8, but I might be wrong.

**Comment by Memnarch** [comment]
Did you use the websetup or do you compile manually?

**Comment by rifoerster** [comment]
Same error here (when compiling)
there is also an error when installing using the Web Installer 

https://pastebin.com/u1GuAKCK

**Comment by rifoerster** [comment]
As the wiki page
http://docwiki.embarcadero.com/Libraries/XE8/en/System.ImageList
first exists in XE8 i also think its a XE8 and up features 
(i.e. http://docwiki.embarcadero.com/Libraries/XE6/en/System.ImageList does not)

**Comment by mariodosreyx** [comment]
Well it does not compile under XE7 because ImageList.DCU is missing; please where can i find it?
Best regards

**Comment by Memnarch** [comment]
@mariodosreyx 
Hi,
Sorry for the late reply. Imagelist or Imglist? I see I am still missing some namespaces on the Imglist references (should be `VCL.ImgList` but ImageList should be `System.Imagelist` in uses section.
Where does it throw the error to be exact?

PS: Next time, please open a new ticket. Quite possible I introduced a regression that reintroduced this problem.
