### ISSUE TITLE
When installation fails the search and browsing paths are not removed again

### ISSUE THREAD

**Issue by sglienke** [Memnarch/Delphinus#8]
Maybe they should be added after compiling the packages. They should not require these paths to be set.

Also the installer does not check if these paths already exist, it keeps adding them over and over.

**Comment by Memnarch** [comment]
the pathes are still there, because the source is still there. A failed installation is not removed automatically(the user has to press uninstall atm). Adding this option to the installer dialog is possible, later.

I'll fix the double searchpathes
