### ISSUE TITLE
[feature request] Allow to install package from a directory (containing Delphinus.{Info|Install}.json files)

### ISSUE THREAD

**Issue by michaliskambi** [Memnarch/Delphinus#89]
As I understand, when installing the package, what Delphinus does is 

1. Get repository as a ZIP from GitHub
2. Unpack it
3. Look into `Delphinus.Install.json` to perform the installation (copy source folders, compile packages, add units to Delphi)

This feature request basically asks to add an option (button on the toolbar) to "Install from a directory". 

- User has to point to a directory that already contains both `Delphinus.Info.json` and `Delphinus.Install.json`. 
- Delphinus just performs "step 3" of the installation -- no need to download or unpack the zip, instead assume that the directory contains already downloaded (in whatever way) contents
- Delphinus can also mark package as installed, looking into GUID in `Delphinus.Info.json`. For future purposes, Delphinus can (hopefully) even just forget that this package was installed from a local directory -- it should be equivalent to installing by downloading. If package with the same GUID is found by scanning GitHub, Delphinus can assume it is the same package.

Reasons for this feature:

- Smaller reason, but not the only one, is to avoid waiting for Delphinus to download the repository. If I have it downloaded already (as a ZIP, or GIT clone) then Delphinus could just use it.

- Bigger reason, important for _Castle Game Engine_: We would be able then to recommend people to download CGE from our standard installers (like a Windows installer linked on top of https://castle-engine.io/download ). These installers unpack *the same thing as we have in GitHub repository* (so whole source code, with `Delphinus.{Info|Install}.json` files) plus some more (precompiled tools, generated API docs, bundled FPC). 

    For CGE users, installing such already-downloaded directory using Delphinus has important benefit: Delphinus would modify Delphi unit paths (so that CGE units are automatically available) and make the Delphi packages built too. This is useful for us -- otherwise doing it manually is a pain for users, as CGE has many paths one has to add. (We have alternative approaches, where CGE editor manages to DPROJ with paths for you, but it's not suitable in all cases.)

**Comment by Memnarch** [comment]
Isn't this what you need? It's already there.
![grafik](https://user-images.githubusercontent.com/1398184/236529670-3d1402c5-b14d-45b9-9afe-64eee05f2245.png)

**Comment by michaliskambi** [comment]
Tested, that's exactly what I needed. I don't know how I missed it :) Sorry for the noise.
